POST http://localhost:9000/api/auth/register
Content-Type: application/json

{
    "username": "     Ryan         ",
    "password": "1234",
    "role_name": "musician"
}

####

POST http://localhost:9000/api/auth/login
Content-Type: application/json

{
    "username": "Ryan",
    "password": "1234"
}

####