GET http://localhost:9000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjozLCJ1c2VybmFtZSI6IkFsZXgiLCJyb2xlX25hbWUiOiJDaGllZiBFeGVjdXRpdmUgT2ZmaWNlciIsImlhdCI6MTcyNDI5Mzc3NywiZXhwIjoxNzI0MzgwMTc3fQ.07VgmTi0mFXLmXJQfGzjSFByQ4ZaT0O5u7_D0IsmfMM

####

GET http://localhost:9000/api/users/2