GET http://localhost:9000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJ1c2VybmFtZSI6ImJvYiIsInJvbGVfbmFtZSI6ImFkbWluIiwiaWF0IjoxNzI0Mjk0NjI3LCJleHAiOjE3MjQzODEwMjd9.jCyg81mTRW5rIfBz77hfD4n8VBFPVeJtTbjdYMx4HOk

####

GET http://localhost:9000/api/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJ1c2VybmFtZSI6ImJvYiIsInJvbGVfbmFtZSI6ImFkbWluIiwiaWF0IjoxNzI0Mjk0NjI3LCJleHAiOjE3MjQzODEwMjd9.jCyg81mTRW5rIfBz77hfD4n8VBFPVeJtTbjdYMx4HOk